FROM node:11.15.0-alpine

# Create application's directory
VOLUME /app
WORKDIR /app

EXPOSE 3000

CMD npm install \
    && rm -rf build \
    && npm run build \
    && npm run typeorm -- migration:run \
    && npm run dev
